{% set name = "lazyslide" %}
{% set version = "0.9.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lazyslide-{{ version }}.tar.gz
  sha256: f4230935c15ed28b1169b85d3265ed314e721d763a0e738add4b0088fa73f709

build:
  entry_points:
    - lazyslide = lazyslide.__main__:app
    - zs = lazyslide.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }}
    - wsidata >=0.6.0
    - scikit-learn >=1.0
    - matplotlib-base >=3.9.0
    - matplotlib-scalebar >=0.9.0
    - legendkit >=0.3.4
    - rich >=13.0.0
    - cyclopts >=3.0.0
    - timm >=1.0.3
    - pytorch >=2.0.0
    - seaborn >=0.12.2
    - psutil >=5.9.0

test:
  imports:
    - lazyslide
  commands:
    - pip check
    - lazyslide --help
    - zs --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rendeirolab/LazySlide
  summary: Modularized and scalable whole slide image analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
    - sarthakpati
